### ISSUE TITLE
Swift 5.9 issue

### ISSUE THREAD

**Issue by giorgio-seguini** [pointfreeco/swift-perception#113]
### Description

Hello, thanks for your effort.

Unfortunately, I am here with a request.
The latest version of swift-perception (`1.4.0`) does not compile on Xcode 15.
I saw that a PR has been already opened and approved #111 . Can you please merge it and release a version with the fix?

### Checklist

- [ ] I have determined that this bug is not reproducible using Swift's observation tools. If the bug is reproducible using the `@Observable` macro or another tool from the `Observation` framework, please [file it directly with Apple](https://github.com/apple/swift/issues/new/choose).
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-perception/issues) or [discussion](https://github.com/pointfreeco/swift-perception/discussions).

### Perception version information

1.4.0

### Destination operating system

Swift 5.x

### Xcode version information

Xcode 15

**Comment by gamael** [comment]
Same issue here. Currently using swift 5.8.1

**Comment by mbrandonw** [comment]
I also believe updating to Xcode 15.4+ will work around the problem in the meantime.

**Comment by mbrandonw** [comment]
This has been fixed and released, so I am closing for now.
