### ISSUE TITLE
No such module 'Perception'

### ISSUE THREAD

**Issue by lanserxt** [pointfreeco/swift-perception#19]
### Description

Hello,

On adding project using SPM (https://github.com/pointfreeco/swift-perception.git), I got 

`No such module 'Perception'`

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-perception/issues) or [discussion](https://github.com/pointfreeco/swift-perception/discussions).

### Expected behavior

`@Perceptible` can be used

### Actual behavior

`No such module 'Perception'`

### Perception version information

1.1.0

### Destination operating system

iOS 17

### Xcode version information

Version 15.2 (15C500b)

### Swift Compiler version information

```shell
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
```

**Comment by lanserxt** [comment]
Perceptionmacros must be enabled

**Comment by lanserxt** [comment]
Perceptionmacros must be enabled. Will be done on first compile.

**Comment by mbrandonw** [comment]
There should be an compilation error in the issue navigator of Xcode that asks you to enable the macro.
