### ISSUE TITLE
Memory leak of Perceptible objects

### ISSUE THREAD

**Issue by beforeold** [pointfreeco/swift-perception#51]
### Description

The model won't deinit when the view dismissed.

seems the WithPerceptionTracking will capture the view and the model through the withPerceptionTracking function

### Checklist

- [X] I have determined that this bug is not reproducible using Swift's observation tools. If the bug is reproducible using the `@Observable` macro or another tool from the `Observation` framework, please [file it directly with Apple](https://github.com/apple/swift/issues/new/choose).
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-perception/issues) or [discussion](https://github.com/pointfreeco/swift-perception/discussions).

### Expected behavior

the model deinitialzed after the view dismissed

### Actual behavior

the model is alive

### Steps to reproduce

1. add a new @State property to Content of the example
```
@State private var showsContentSheet = false
```
2. add a sheet modifier to the body of the ContentView
```
.sheet(isPresented: $showsContentSheet) {
      ContentView(model: .init())
    }
```

3. add a button to the Form of the ContentView to show the sheet with a brand new ContentView
```
    Button("Present new ContentView") {
          self.showsContentSheet = true
        }
```
4. add a deinit log for the model the CounterModel
```
deinit {
    print(self, "deinit")
  }
```
5. Run the example, Tap the Present new ContentView button, and drag to dismiss the new ContentView
expectation falure for the deinit log

### Perception version information

db087559dcc50eedebdc7df6a0fb0c1e188e4229

### Destination operating system

iOS 16.7.3

### Xcode version information

Xcode 15.0.1

### Swift Compiler version information

```shell
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
```

Here is the demo project:  [this repo](https://github.com/beforeold/ObservationMemoryLeak).

**Comment by mbrandonw** [comment]
Hi @beforeold, can you please provide a project that demonstrates the problem?

**Comment by beforeold** [comment]
> Hi @beforeold, can you please provide a project that demonstrates the problem?

Hi @mbrandonw Thanks for your reply. Here is the exmaple. Please checkout the PerceptionExampleView in [this repo](https://github.com/beforeold/ObservationMemoryLeak).

**Comment by mbrandonw** [comment]
Thank you for the project, that helps. I can definitely see the issue. I imagine we will need to make use of some of the [internal `withObservationTracking` functions](https://github.com/apple/swift/blob/784a7c5e3172c9a8a51a3a9136a02e678957f464/stdlib/public/Observation/Sources/Observation/ObservationTracking.swift#L240) so that we can explicitly cancel observation. We will look into this sometime soon, but we do have some travel planned currently and so we are not sure when.

**Comment by stephencelis** [comment]
Thanks for the repro! We think that using the SPI API in Observation here would allow us to cancel observations when views go away:

https://github.com/apple/swift/blob/784a7c5e3172c9a8a51a3a9136a02e678957f464/stdlib/public/Observation/Sources/Observation/ObservationTracking.swift#L240

We won't have time to look into a fix for a couple weeks as we'll be traveling for try! Swift, but if anyone else was curious about fixing, we figure it'd be good to surface things here.

If no one else looks into it in the meantime, we'll take a look in the coming weeks!

**Comment by beforeold** [comment]
Cool, Very glad to hear there is a possible solution. Let me know if I can do some favor.

Wish you have a nice trip.
