### ISSUE TITLE
1.2.0 breaks visionOS due to ambiguous `@Bindable`

### ISSUE THREAD

**Issue by josephquigley** [pointfreeco/swift-perception#76]
### Description

When using v1.2.0, visionOS targets that use `@Bindable` and the Perception library do not compile. Downgrading to v1.1.7 temporarily fixes this problem.

### Checklist

- [X] I have determined that this bug is not reproducible using Swift's observation tools. If the bug is reproducible using the `@Observable` macro or another tool from the `Observation` framework, please [file it directly with Apple](https://github.com/apple/swift/issues/new/choose).
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-perception/issues) or [discussion](https://github.com/pointfreeco/swift-perception/discussions).

### Expected behavior

Declaring a `@Bindable var foo: Foo` field on visionOS should compile.

### Actual behavior

Declaring a `@Bindable var foo: Foo` field on visionOS results in a compiler error with the message `'Bindable' is ambiguous for type lookup in this context`

### Steps to reproduce

Create a visionOS target, import `Perception` and attempt to declare a Bindable variable to an `@Observable` type.
```swift
import SwiftUI
import RealityKit
import RealityKitContent
import Perception

@Observable
class Foo {

}

struct ContentView: View {
    @Bindable var foo: Foo // 'Bindable' is ambiguous for type lookup in this context

    var body: some View {
        EmptyView()
    }
}

#Preview(windowStyle: .automatic) {
    ContentView(foo: Foo())
}
```

### Perception version information

1.2.0

### Destination operating system

visionOS 1.1

### Xcode version information

15.3

### Swift Compiler version information

```shell
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

**Comment by stephencelis** [comment]
@josephquigley We made a few changes last version to silence deprecation warnings that would show up in visionOS projects, and some of those changes made perception types more available to visionOS. I guess I'm confused, though. If you are importing `Perception` into a file, then you likely need to use `Perception.Bindable`, and so this build failure makes sense in requiring you to specify `SwiftUI.Bindable` vs. `Perception.Bindable`. I think the bug around warnings we fixed may have just been hiding this issue on visionOS that was already happening on other platforms. Is it possible you just need to remove that import?

**Comment by josephquigley** [comment]
@stephencelis We're not importing this directly on our project, we're using TCA, but when I looked at the dependencies only the Perception library was updated within the last 24 hours when our visionOS builds stopped building. I downgraded to Perception 1.1.7 by manually including it in my project dependencies which resolved the issue, so I opened a bug here instead of on TCA.

**Comment by josephquigley** [comment]
I can reproduce it by directly importing TCA. Project and screenshot attached:
[BindableOnVisionOS.zip](https://github.com/pointfreeco/swift-perception/files/15504699/BindableOnVisionOS.zip)

![Screenshot 2024-05-30 at 3 06 30 PM](https://github.com/pointfreeco/swift-perception/assets/682509/e34a50f0-e1aa-4290-940e-127753635d65)

For some reason, importing `ComposableArchitecture` also tries to bring in the perception macros on visionOS:
![Screenshot 2024-05-30 at 3 05 54 PM](https://github.com/pointfreeco/swift-perception/assets/682509/e2760847-d0e4-47c0-b561-ab7be7f59892)

**Comment by stephencelis** [comment]
@josephquigley Can you give this branch a try? https://github.com/pointfreeco/swift-perception/pull/77

**Comment by josephquigley** [comment]
@stephencelis Confirmed this resolves the issue when importing TCA and/or Perception. Thanks!
