### ISSUE TITLE
'Bindable' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by JackMoseley2001** [pointfreeco/swift-perception#79]
### Description

Hi 👋 

Since the latest update (v1.2.1) it appears that projects on this version but building for iOS 17 now get a "Bindable is ambiguous" error, I suspect due to the removal of:

```swift
@available(iOS, introduced: 13, obsoleted: 17, message: "Use @Bindable without the 'Perception.' prefix.")
@available(macOS, introduced: 10.15, obsoleted: 14, message: "Use @Bindable without the 'Perception.' prefix.")
@available(tvOS, introduced: 13, obsoleted: 17, message: "Use @Bindable without the 'Perception.' prefix.")
@available(watchOS, introduced: 6, obsoleted: 10, message: "Use @Bindable without the 'Perception.' prefix.")
```

within the backported version of `Bindable`. I noticed this was in aid of fixing the issue for VisionOS (Issue https://github.com/pointfreeco/swift-perception/issues/76), but seems to have had a knock on effect for other projects. Was there a reason to remove these availability checks? It appears that these checks were enough to keep the compiler happy for iOS 17 projects.

The issue is resolved when pinning Perception to `1.2.0`.

Would a suitable solution be to revert these availability checks for now?

Thank you! 🙏 

### Checklist

- [X] I have determined that this bug is not reproducible using Swift's observation tools. If the bug is reproducible using the `@Observable` macro or another tool from the `Observation` framework, please [file it directly with Apple](https://github.com/apple/swift/issues/new/choose).
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-perception/issues) or [discussion](https://github.com/pointfreeco/swift-perception/discussions).

### Perception version information

1.2.1

### Destination operating system

iOS 17

### Xcode version information

15.3

### Swift Compiler version information

```shell
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

**Comment by mbrandonw** [comment]
Hi @JackMoseley2001, good catch! Have a PR [here](https://github.com/pointfreeco/swift-perception/pull/80) and will get a release out soon.

**Comment by JackMoseley2001** [comment]
> Hi @JackMoseley2001, good catch! Have a PR [here](https://github.com/pointfreeco/swift-perception/pull/80) and will get a release out soon. 

That's great, thank you for such a swift resolution! Really appreciate all the work you guys do! 💪
