### ISSUE TITLE
"was accessed but is not being tracked" warning may be too noisy

### ISSUE THREAD

**Issue by rudro** [pointfreeco/swift-perception#9]
### Description

Decided to take a super simple SwiftUI project and add Perception to it.  Picked : https://github.com/twostraws/HackingWithSwift/tree/main/SwiftUI/project7

Saw several warnings show up, and that was great when I hadn't added the WithPercep...

However, after my fixes, I still am seeing the warning.  I realize now that it's due to this simple bit of code : https://github.com/twostraws/HackingWithSwift/blob/main/SwiftUI/project7/iExpense/ContentView.swift#L76

When you delete an expense, it removes an item from the array (which is Perceptible) and in order to remove, it has to perform a read which when triggers the warning. 

So the maybe the warning should not only check for the presence of and update without a WithPerceptionTracking in the stack, but it also needs to see that the access is being made in the context of SwiftUI and not in some place where I may not care about tracking updates.

Hope this made sense.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-perception/issues) or [discussion](https://github.com/pointfreeco/swift-perception/discussions).

**Comment by rudro** [comment]
Ah, ignore my suggestion at the end. I see the `isInSwiftUIBody` function does try to do what I suggested. The problem is that the mutation is initiated from a SwiftUI view.

**Comment by mbrandonw** [comment]
This will be fixed in #10. We had special logic to handle `onDelete { delete(…) }`, but not `onDelete(perform: delete)`.

You will see additional perception warnings due to the assigning of `items` in the [initializer](https://github.com/twostraws/HackingWithSwift/blob/751d180e8fe811390bb8e1d2b475bd988b53fdf2/SwiftUI/project7/iExpense/ContentView.swift#L30-L35). To fix that you will need to use `_items` in the initializer.
